### ISSUE TITLE
Debian packages has hard coded dependencies

### ISSUE THREAD

**Issue by egilh** [enaess/network-manager-sstp#10]
Having previously ran sstp-client and network-manager-sstp successfully, I tried to install them on my laptop running Ubuntu MATE 16.04 (beta2).
First of all: This is a beta, so I don't expect everything to work.

The problem however, is that the debian package depends on an older version of PPP, this seems to also be hardcoded into the debian packages for sstp-client, making it more or less impossible to make it run.
I have downloaded the packages and changed dependencies to be able to install, but this hardcoding of versions in the debian package is what I would consider a bug.

Would it be possible to change this, so that sstp-client and network-manager-sstp don't have a hardcoded dependency to ppp 2.4.6?

**Comment by enaess** [comment]
Seems like something that needs to be fixed soon.
 

    On Wednesday, April 13, 2016 4:37 AM, Egil Haugli <notifications@github.com> wrote:
 

 Having previously ran sstp-client and network-manager-sstp successfully, I tried to install them on my laptop running Ubuntu MATE 16.04 (beta2).
First of all: This is a beta, so I don't expect everything to work.The problem however, is that the debian package depends on an older version of PPP, this seems to also be hardcoded into the debian packages for sstp-client, making it more or less impossible to make it run.
I have downloaded the packages and changed dependencies to be able to install, but this hardcoding of versions in the debian package is what I would consider a bug.Would it be possible to change this, so that sstp-client and network-manager-sstp don't have a hardcoded dependency to ppp 2.4.6?—

**Comment by egilh** [comment]
I see that there are new packages out for Xenial, thanks alot for that.
However, I'm having some issues to connect, where I'm not sure if the problem is with network-manager-sstp or Mate (running Ubuntu Mate 16.04).

After having created a sstp connection in the GUI, whenever I try to connect it fails with the following log message:
```
Apr 29 12:03:13 NO-LAB-SC-008 NetworkManager[897]: <info>  [1461924193.4867] audit: op="connection-activate" uuid="d8f0a23e-70fe-43a4-b476-97175c765b66" name="Visma" pid=2033 uid=1000 result="fail" reason="The VPN service 'org.freedesktop.NetworkManager.sstp' was not installed."
```

**Comment by egilh** [comment]
This is a bug in the package.
nm-sstp-service.name is not put in /usr/lib/NetworkManager/VPN

I copied it over from /etc/NetworkManager/VPN, seems to be working fine now.

**Comment by enaess** [comment]
Thank you Egil, I'll have a look at this soon as I am in the middle of merging more changes to the project.
- Eivind
 

    Den Fredag, 29. april 2016 5.34 skrev Egil Haugli <notifications@github.com>:
 

 This is a bug in the package.
nm-sstp-service.name is not put in /usr/lib/NetworkManager/VPNI copied it over from /etc/NetworkManager/VPN, seems to be working fine now.—

**Comment by enaess** [comment]
Let me know if this is still an issue.
