### ISSUE TITLE
Ubuntu 18.04 LTS Bionic Beaver compatibility

### ISSUE THREAD

**Issue by kristofejro** [enaess/network-manager-sstp#27]
Hi,
Is network-manager-sstp supposed to work with Ubuntu 18.04 LTS Bionic Beaver?
I have test machine with clean installation of that Ubuntu and it cannot be installed.

This is what I have:
```
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 61FF9694161CE595 
Added below two lines into the following file: /etc/apt/sources.list.d/sstp-client.list 
deb http://ppa.launchpad.net/eivnaes/network-manager-sstp/ubuntu bionic main
deb-src http://ppa.launchpad.net/eivnaes/network-manager-sstp/ubuntu bionic main

apt-get update
apt-get install network-manager-sstp sstp-client

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 network-manager-sstp : Depends: ppp (< 2.4.7-2~) but 2.4.7-2+2ubuntu1 is to be installed
 sstp-client : Depends: libevent-2.0-5 (>= 2.0.10-stable) but it is not installable
               Depends: ppp (< 2.4.7-2~) but 2.4.7-2+2ubuntu1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

Any advice would be appreciated.

**Comment by enaess** [comment]
Cool, I'll see if I can get this one sorted out soon.

**Comment by enaess** [comment]
Thanks for reporting it.

**Comment by sdokara** [comment]
The `sstp-client` might need modifications for bionic first. 
Either use `libssl1.0.0` and install `libssl1.0-dev` explicitly, or use my branch for `libssl1.1`. It also installs the plugin for `ppp` in `/usr/lib/pppd/2.4.5` (Ubuntu comes with 2.4.7 since xenial, but 2.4.5 seems to be hardcoded, and the `configure` switch for it doesn't seem to work). Adding the full path to `plugin` in `/etc/ppp/peers/` files or moving the plugin files worked. Also, the `sstp-sock` path was wrong (had to prepend `/usr/local` to `/var/run/sstpc/sstpc-uds-sock`), but this is all for another project :).

I've made the `sstp-client` work somehow, but was unable to integrate `network-manager-sstp` still.
What I've seen funny so far are the folders. I used `--prefix=/usr` and got:
- `nm-sstp-service.conf` installed in `/usr/etc/dbus-1/system.d/`;
- `nm-sstp-auth-dialog` and `nm-sstp-service` installed in `/usr/libexec/`, but the `nm-sstp-service.name` pointed to `/usr/local/libexec/`;
After some fixes, `nm-connection-editor` says:
```
vpn: (sstp,/usr/lib/NetworkManager/VPN/nm-sstp-service.name) file "libnm-vpn-plugin-sstp.so" not found. Did you install the client package?
```
even though the file is there.
When I set the full path, I get:
```
/usr/local/lib/NetworkManager/libnm-vpn-plugin-sstp-editor.so
``
Could not load editor VPN plugin for “org.freedesktop.NetworkManager.sstp” (missing plugin file "/usr/local/lib/NetworkManager/libnm-vpn-plugin-sstp-editor.so").
```
So, the `prefix` thingy doesn't work quite well.

Without the prefixes (both on `sstp-client` and `network-manager-sstp`), I had to move the `nm-sstp-service.conf` only and got the dialogs set up. But, the connection fails with
```
NetworkManager[13586]: /usr/sbin/pppd: /usr/local/lib/pppd/2.4.7/nm-sstp-pppd-plugin.so: undefined symbol: sstp_api_msg_new
```

**Comment by enaess** [comment]
Could you sync your Ubuntu Bionic Beaver distribution with the PPA and try to re-install the packages again?

**Comment by kristofejro** [comment]
Good job enaess!
In my case it installs without any issue now.

**Comment by killua-eu** [comment]
@enaess, just a quick THANK YOU for the whole network-manager-sstp project, I really apprecaite it.
