### ISSUE TITLE
sstp-client : Depends: libevent-2.1-6 (>= 2.1.8-stable) but it is not installable

### ISSUE THREAD

**Issue by jamesmacwhite** [enaess/network-manager-sstp#36]
Hi,

I was trying to install `sstp-client` through the PPA, but get the error as titled. I'm running Kali Linux which is based on Debian testing under the hood. None of the PPA dists seem to work under Kali, I tried a few, all bailing out with libevent issues.

This is my libevent library package/version:

> libevent-2.1-7/kali-rolling,now 2.1.11-stable-1 amd64 [installed,automatic]
  Asynchronous event notification library

Is it the libevent version that Kali Linux rolling is shipping the issue? Just wondering if there's a quick way to resolve, or should I compile from source?

Thanks

**Comment by enaess** [comment]
Hi James,
The packages available at my hosted PPA on launchpad is designed to work with Ubuntu. You should probably look into (re-)compiling the packages for your particular distribution in case any libraries have missing symbols or changed their ABI. If Linux/Kali supports apt-get (apptitude) "apt-get build-dep <sstp-client>, apt-get source <sstp-client> you may look into re-building the .deb files Kali, if not try looking at the configure statement and see if you can adjust it for Kali and how it expects the paths to be setup.
I am in progress of adding certificate support for use with Microsoft Azure, so you do not want to take the latest tip of the source code trees, but rather sync using git/svn to the appropriate version(s).

Regards,- Eivind

    På søndag 5. april 2020, 10:04:58 PDT skrev James White <notifications@github.com> følgende:  
 
 


Hi,

I was trying to install sstp-client through the PPA, but get the error as titled. I'm running Kali Linux which is based on Debian testing under the hood. None of the PPA dists seem to work under Kali, I tried a few, all bailing out with libevent issues.

This is my libevent library package/version:


libevent-2.1-7/kali-rolling,now 2.1.11-stable-1 amd64 [installed,automatic]
Asynchronous event notification library


Is it the libevent version that Kali Linux rolling is shipping the issue? Just wondering if there's a quick way to resolve, or should I compile from source?

Thanks

**Comment by jamesmacwhite** [comment]
@enaess Thanks for your reply! No worries, thanks for the additional info and guidance. I appreciate that they aren't directly compatible with Debian. I came across your PPA from this question on the Unix StackExchange here: https://unix.stackexchange.com/questions/512508/building-sstp-client-on-kali-linux-from-source-dpkg-errors. At the time it looks like it may have worked for Kali but that was back in April 2019, so a lot has changed since then!

I'll see if I can compile a deb myself or just build from source.

Thanks again!

**Comment by enaess** [comment]
Cool, 

The latest version is sstp-client-1.0.13 (and not 1.0.12 as suggested by that post). Also, "apt-get source sstp-client" will get you the files (including the debian build directory) that is missing according to that stackexchange article

- Eivind

    På søndag 5. april 2020, 11:15:32 PDT skrev James White <notifications@github.com> følgende:  
 
 


@enaess Thanks for your reply! No worries, thanks for the additional info and guidance. I appreciate that they aren't directly compatible with Debian. I came across your PPA from this question on the Unix StackExchange here: https://unix.stackexchange.com/questions/512508/building-sstp-client-on-kali-linux-from-source-dpkg-errors. At the time it looks like it may have worked for Kali but that was back in April 2019, so a lot has changed since then!

I'll see if I can compile a deb myself or just build from source.

Thanks again!

**Comment by jamesmacwhite** [comment]
Thanks for this! I have managed to compile sstp-client as a compatible deb which does install on Kali and the binary works at /usr/sbin/sstpc. I'll do some testing to see if I can get a connection with sstpc and look at the NetworkManager stuff if I can connect!

**Comment by enaess** [comment]
Sweet!
Just to be noted, the network-manager-sstp github repository is in progress of being reworked to incorporate the certificate support and may not compile if you sync it to the tip-of the source code right now. Use the "apt-get source network-manager-sstp" may be the way to go.

Regards,
- Eivind

    På søndag 5. april 2020, 12:05:27 PDT skrev James White <notifications@github.com> følgende:  
 
 


Thanks for this! I have managed to compile sstp-client as a compatible deb which does install on Kali and the binary works at /usr/sbin/sstpc. I'll do some testing to see if I can get a connection with sstpc and look at the NetworkManager stuff if I can connect!

**Comment by jamesmacwhite** [comment]
Thanks, I have also rebuilt the network-manager-sstp deb from 1.2.6 and it's installed OK and I've managed to get a successful connection!

One thing though, does sstpc support IPv6? Using my SSTP DNS for the VPN hostname threw invalid address family errors, but using IPv4 literal worked. I'm assuming it's because in DNS my SSTP VPN does have an AAAA record, does sstpc only work with IPv4?

**Comment by enaess** [comment]
I can't remember the details, but the ipv6 negotiation failed for some reason and just to be able to connect I had to disable the ipv6 option. I don't know if this has changed with ppp in a later version / release, but you could try editing the nm-sstp-service.c file and comment out the "noipv6" statement and recompile:


src/nm-sstp-service.c around line 536:
 
|  /* PPP options */ |
|


|  // g_ptr_array_add (args, (gpointer) g_strdup ("noipv6")); |
|


|  g_ptr_array_add (args, (gpointer) g_strdup ("ipparam")); |
|

 g_ptr_array_add (args, (gpointer) ipparam);

    På søndag 5. april 2020, 12:29:13 PDT skrev James White <notifications@github.com> følgende:  
 
 


Thanks, I have also rebuilt the network-manager-sstp deb from 1.2.6 and it's installed OK and I've managed to get a successful connection!

One thing though, does sstpc support IPv6? Using my SSTP DNS for the VPN hostname threw invalid address family errors, but using IPv4 literal worked. I'm assuming it's because in DNS my SSTP VPN does have an AAAA record, does sstpc only work with IPv4?

**Comment by jamesmacwhite** [comment]
Ah, so it is IPv6, thanks for the info. I'll recompile with noipv6 removed and see if I can get an connection! Thanks for the tip.
