### ISSUE TITLE
No Fedora-Repo found for network-manager-sstp

### ISSUE THREAD

**Issue by Cyber1000** [enaess/network-manager-sstp#5]
Is there a build rpm in a current Fedora-Repo? In the official repos it is not included as far as I can see.

**Comment by enaess** [comment]
Not currently, but I am working on changes to update it so you could build it from source for the Fedora project. Changes are done, need to do some more testing.

**Comment by szpak** [comment]
When I tried to compile manual and run it on Fedora 21 a few months ago it failed due incompatibility with current GnomeKeyring. @enaess Have you managed to make it work with current Fedora (I don't see new commit in a repo)?

**Comment by enaess** [comment]
I have not tried to compile it on Fedora, but I have been able to bring the project up to date with the current network-manager-pptp project. Should also have dealt with the keyring problem. Hoping to be able to commit those changes this week or next.

**Comment by Cyber1000** [comment]
As far as I have tested in a vm (so only short testing) I could take networkmanager-sstp from here http://sourceforge.net/projects/sstp-client/files/network-manager-sstp/. It's fedora 18 release and you have to install it with nodeps cause of a newer pppd in current fedora.

Thanks for the information! I'll update my fedora to the new fedora 22 release in a few weeks and it would be nice if there is a current package (and even nicer if there is just a repo, so I don't have to compile myself :-) )

Regards

**Comment by szpak** [comment]
Big thanks @enaess for your modification! I've just tested it on Fedora 21 and it worked flawlessly.

I built RPM packages from your SPEC file , but I wonder if you plan to put it into the official Fedora repository to be available for all Fedora users?

Btw, I had to create a source package from Git repository. Is there a tar.bz2 archive for 1.1.0?

**Comment by enaess** [comment]
Hi Szpak,
I can upload the latest changes to sourceforge for FC22, but I really am hoping that someone over at Fedora / RedHat are able to maintain this. It used to be in their repository, but I think the source code was outdated and they dropped it. I am hopeful that they would pick it up again.

**Comment by enaess** [comment]
I was able to create and maintain my own PPA over at launchpad.net for Ubuntu like distributions. Launchpad seems easy enough to be able to upload packages.

**Comment by szpak** [comment]
If you planned to maintain the project itself in the reasonable future (i.e. keep it compatible with the new NetworkManager releases) I could probably try to put the RPMs back to the official Fedora repo (although it usually take time to put it through).

**Comment by szpak** [comment]
Btw, I haven't been using Launchpad for years, but as an alternative there is also Bintray - https://bintray.com/docs/usermanual/whatisbintray/whatisbintray_supportedsoftwaretypes.html.

**Comment by enaess** [comment]
Thank you for the suggestion as I wasn't aware of Bintray. However, that won't solve your FC22 problem. I think it always been the plan to keep maintaining this, and keep it up to date with NetworkManager project. Didn't seem like any of the NetworkManager guys over at RedHat was interested in the project.

Over the past few years, I didn't receive any of the github.com requests that people put in (configuration problem). On occasions, I'll get a question on sstp-client if something isn't working right. In open source development, it seems like most people won't take their time if things isn't working right to bother report it. A little nudge does work every so often to keep the ball moving. If changes needs to be done in the future, I'd love to hear about them and also work on them to the extent that my spare time permits it.

Any help you or anybody else can offer is definitely appreciated.

**Comment by szpak** [comment]
Hmm, in fact I don't have a F22 problem. I was able to build it locally for F21 and probably I will be able to build it for F22 when I upgrade to it. I only like to have the software I use in the official Fedora repository.

I asked about your plans to maintain the project as from my Fedora packager maintenance it takes some time to put a package to the Fedora official repository and it would be a waste of time if it would be removed after a few months due to (for example) an incompatibility with the new NetworkManager version used in Fedora 23. Glad to hear that you plan to do that!

To explain my question a few months ago I tried to use network-manager-sstp with Fedora 21 and it failed to compile with current NetworkManager and even with treating depreation errors as warnings it didn't work. Seeing handing #3 and #4 I thought the project is no longer maintained and I only subscribe to existing issues. Probably I could be more verbose and raise a new, more precise issue. I will not hesitate to do that in the future (if needed :) ).

**Comment by enaess** [comment]
Thank you! I have another change I plan to commit, pretty much an update to the .spec and README files. I had some issue installing the FC22 live CD on my VMWare Fusion installation and had to grab the low-graphic internet installer. I'll be up and running again on FC22 soon. The FC21/22 version NetworkManager has different versions, but they seem to be mostly compatible from the perspective of network-manager-sstp point of view (no bugs yet). You should be able to compile either one from source.

**Comment by szpak** [comment]
Ok, take your time. Please let me know if there is a final tarball of 1.1.0 available to download (which is required to submit package to Fedora).

**Comment by szpak** [comment]
In the meantime my colleague tested it with Fedora 22 and it seems to work fine.

Btw, I've seen you made changes in README and other files. Do you plan to make anything else or you just need to upload a 0.9.10 tarball somewhere?

**Comment by enaess** [comment]
I uploded the new version for FC22 to sourceforge.net. The .rpm spec was cloned from latest FC distribution of the pptp counterpart and should be compatible with the latest network-manager project (1.0). 
Look for the sstp-client project on the download page. 
- Eivind


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by szpak** [comment]
I've seen http://sourceforge.net/projects/sstp-client/files/network-manager-sstp/0.9.10-1/, but there is still no the official tarball with sources (which is needed to build a package from a SPEC file and which has to available to download as a separate file - not a part of `src.rpm` - to be put into Fedora). Is it available anywhere?

**Comment by enaess** [comment]
Oh! I see what you mean now. I will upload it tomorrow. The way I built the rpm was to sync down the sources from git or use the tar.gz from sourceforge and type ./configure, then make dist-bzip2 (check the make targets). Put the resulting tarball in ~/rpmbuild/SOURCES and build it for FC using the .spec file in the source tree.
Regards,- Eivind


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by enaess** [comment]
I uploaded both the .tar.bz2 file and the .src.rpm to the sourceforge web-site. Please check it out and let me know if that meets you requirements.
- Eivind 


     On Sunday, June 7, 2015 3:56 PM, Marcin Zajączkowski <notifications@github.com> wrote:
   

 I've seen http://sourceforge.net/projects/sstp-client/files/network-manager-sstp/0.9.10-1/, but there is still no the official tarball with sources (which is needed to build a package from a SPEC file and which has to available to download as a separate file - not a part of src.rpm - to be put into Fedora). Is it available anywhere?—

**Comment by szpak** [comment]
It look fine, thanks.

Btw, there are Obsoletes tags which look like taken exactly from NetworkManager-pptp package:
> Obsoletes: NetworkManager-sstp < 1:0.9.8.2-3

Do you see any reason to keep them?

**Comment by enaess** [comment]
The version by itself is probably wrong, and it should probably obsolete the old version in the repository. However, I don't see any specific reason to obsolete the package other than replace the older package when the new upgrade is in place. Is this causing a specific problem for you?
- Eivind 


     On Monday, June 8, 2015 3:12 PM, Marcin Zajączkowski <notifications@github.com> wrote:
   

 It look fine, thanks.Btw, there are Obsoletes tags which look like taken exactly from NetworkManager-pptp package:
Obsoletes: NetworkManager-sstp < 1:0.9.8.2-3
Do you see any reason to keep them?—

**Comment by szpak** [comment]
No, I was just removing rpmlint warnings and I wondered if it is still needed. I will remove "Obsolete" tags, in that case.

**Comment by szpak** [comment]
I've made a [review request](https://bugzilla.redhat.com/show_bug.cgi?id=1229903).

**Comment by enaess** [comment]
Very cool! Marcin, did you want me to commit these changes to the git repository too?- Eivind 


     On Tuesday, June 9, 2015 2:48 PM, Marcin Zajączkowski <notifications@github.com> wrote:
   

 I've made a review request.—

**Comment by szpak** [comment]
I propose to wait for comments from a review request and then I will make a complete pull request.

**Comment by Cyber1000** [comment]
If you are searching for a ppa-like thing like launchpad for ubuntu, there is a project called copr which seems to be exactly the same for fedora, rhel-builds. I'm using some of them by now, not sure how easy that would be for you to integrate, just a information.

https://copr.fedoraproject.org/

**Comment by szpak** [comment]
@Cyber1000 The main advantage of being in the official Fedora package is that every Fedora user can install NetworkManager-sstp with just `yum/dnf install NetworkManager-sstp NetworkManager-sstp-gnome`. Nothing to configure manually.

Of course I agree that Corp is a very nice alternative to be used as a temporary solution or in case of problems with the review process :). Thanks for let us know about that.

**Comment by szpak** [comment]
Playing with Corp I've created a temporary repository with packages for Fedora 21 and 22. More details and installation instruction: https://copr.fedoraproject.org/coprs/szpak/NetworkManager-sstp/

Thanks @Cyber1000 once again for telling us about Corp.

Btw, @enaess when I was trying to build that package for Fedora 20 it turned out that `configure` requires NM 0.9.10+. I assume that it is due to your recent changes adjusting the plugin to changes in 0.9.10, so I will add that requirement also in a SPEC file.

**Comment by enaess** [comment]
Hi Marcin,
Looks to me that the change that originally induced this was made to support password dialog and libsecret which required the libnm-gtk >= 0.9.9.0 back in April 2013. There's a few changes after that, but not having actually tried this; it should technically still work if you edit the configure.ac w.r.t. NetworkManager version numbers. There's still a few real changes in the NetworkManager-pptp project after this so it's not completely clear if it will still link. Supporting FC 21, 22 and also 23, would it not be time for most people to upgrade if they run FC 20 and earlier?

Regards,
- Eivind


 


     On Thursday, June 11, 2015 12:54 PM, Marcin Zajączkowski <notifications@github.com> wrote:
   

 Playing with Corp I've created a temporary repository with packages for Fedora 21 and 22. More details and installation instruction: https://copr.fedoraproject.org/coprs/szpak/NetworkManager-sstp/Thanks @Cyber1000 once again for telling us about Corp.Btw, @enaess when I was trying to build that package for Fedora 20 it turned out that configure requires NM 0.9.10+. I assume that it is due to your recent changes adjusting the plugin to changes in 0.9.10, so I will add that requirement also in a SPEC file.—

**Comment by szpak** [comment]
Fedora 20 is reaching EOL very soon. In addition older version of NM-sstp would probably work with older NM.
